<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Nasywa Fadhila">
<meta name="dcterms.date" content="2024-12-28">

<title>Pengaruh External Debt Stock terhadap GDP Tahun 2023</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Pengaruh External Debt Stock terhadap GDP Tahun 2023</h1>
<p class="subtitle lead">Metode Penelitian Politeknik APP Jakarta</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Nasywa Fadhila </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">December 28, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="poltekapp.jpg" class="img-fluid figure-img"></p>
<figcaption>logo</figcaption>
</figure>
</div>
<style>
p {text-align: justify;}
</style>
<section id="pendahuluan" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="pendahuluan"><span class="header-section-number">1</span> Pendahuluan</h2>
<section id="latar-belakang" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="latar-belakang"><span class="header-section-number">1.1</span> Latar belakang</h3>
<p>Utang luar negeri (external debt) merupakan salah satu instrumen pembiayaan yang sering digunakan oleh negara untuk mendukung pembangunan ekonomi. Meskipun utang dapat memberikan manfaat dalam hal peningkatan investasi dan pertumbuhan ekonomi, terdapat kekhawatiran bahwa utang yang tinggi dapat berdampak negatif terhadap ekonomi suatu negara, termasuk Produk Domestik Bruto (GDP).</p>
<p>Dalam konteks negara berkembang, utang luar negeri sering kali digunakan untuk membiayai proyek-proyek infrastruktur, pendidikan, dan kesehatan yang bertujuan untuk meningkatkan kapasitas produksi dan kualitas hidup masyarakat. Namun, jika utang tidak dikelola dengan baik, hal ini dapat mengakibatkan beban kewajiban yang berat, yang pada gilirannya dapat menghambat pertumbuhan ekonomi dan mengurangi kemampuan negara untuk berinvestasi dalam pembangunan jangka panjang.</p>
<p>Penelitian sebelumnya menunjukkan bahwa terdapat hubungan yang kompleks antara utang luar negeri dan pertumbuhan ekonomi. Di satu sisi, utang dapat merangsang pertumbuhan dengan menyediakan modal yang diperlukan untuk investasi. Di sisi lain, utang yang berlebihan dapat menghasilkan biaya bunga yang tinggi dan mengalihkan sumber daya dari pengeluaran produktif ke pembayaran utang, yang dapat menghambat pertumbuhan GDP.</p>
<p>Faktor-faktor lain, seperti kebijakan moneter, stabilitas politik, dan kondisi ekonomi global, juga dapat memengaruhi hubungan antara utang luar negeri dan GDP. Oleh karena itu, penting untuk mengeksplorasi bagaimana stok utang luar negeri dapat memengaruhi pertumbuhan ekonomi suatu negara, terutama dalam konteks negara berkembang yang sering kali bergantung pada utang luar negeri untuk mendanai pembangunan.</p>
<p>Melalui penelitian ini, diharapkan dapat memberikan pemahaman yang lebih mendalam mengenai dampak stok utang luar negeri terhadap pertumbuhan GDP, serta memberikan rekomendasi bagi pembuat kebijakan dalam merumuskan strategi pengelolaan utang yang berkelanjutan. Penelitian ini juga diharapkan dapat berkontribusi pada literatur yang ada mengenai ekonomi makro dan pengelolaan utang di negara berkembang.</p>
</section>
<section id="ruang-lingkup" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="ruang-lingkup"><span class="header-section-number">1.2</span> Ruang lingkup</h3>
<p>Penelitian ini menggunakan data yang diperoleh melalui package WDI yang diakses menggunakan perangkat lunak R. Data yang digunakan mencakup dua variabel utama, yaitu External Debt Stock (utang luar negeri) sebagai variabel X dan GDP (Produk Domestik Bruto) sebagai variabel Y. Data tersebut mencakup negara-negara yang terdaftar di World Bank dan merepresentasikan kondisi pada tahun 2023.</p>
</section>
<section id="rumusan-masalah" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="rumusan-masalah"><span class="header-section-number">1.3</span> Rumusan masalah</h3>
<p>Penelitian ini akan menjawab persoalan mengenai:</p>
<ol type="1">
<li>Seberapa besar pengaruh external debt stock terhadap GDP?</li>
<li>Apa saja faktor yang ditimbulkan dari external debt stock terhadap GDP?</li>
<li>Apa tantangan yang dihadapi Indonesia external debt stock?</li>
</ol>
</section>
<section id="tujuan-dan-manfaat-penelitian" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="tujuan-dan-manfaat-penelitian"><span class="header-section-number">1.4</span> Tujuan dan manfaat penelitian</h3>
<p>Tujuan penelitian ini dirumuskan untuk memberikan manfaat bagi pemerintah dan masyarakat, dengan fokus pada pengaruh external debt stock terhadap GDP indonesia :</p>
<p><em>1.</em> <em>Bagi Pemerintah</em></p>
<p>Memberikan rekomendasi kebijakan yang berbasis data untuk meningkatkan kewaspadaan pemerintah akan external debt stock yang mempengaruhi GDP indonesia. Mengidentifikasi strategi yang dapat digunakan pemerintah untuk mengoptimalkan pemanfaatan external debt stock, sehingga dapat mendukung pertumbuhan ekonomi yang berkelanjutan.</p>
<p><em>2.</em> <em>Bagi Masyarakat</em></p>
<p>Meningkatkan kesadaran publik mengenai peran external debt stock terhadap GDP indonesia dan dampaknya terhadap kesejahteraan masyarakat. Mendorong partisipasi masyarakat dalam proses pengambilan keputusan terkait external debt stock, dengan memahami implikasi dari kebijakan tersebut terhadap kehidupan sehari-hari mereka.</p>
</section>
<section id="package" class="level3" data-number="1.5">
<h3 data-number="1.5" class="anchored" data-anchor-id="package"><span class="header-section-number">1.5</span> Package</h3>
<p>Packages yang digunakan antara lain sebagai berikut:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(WDI)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="studi-pustaka" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="studi-pustaka"><span class="header-section-number">2</span> Studi pustaka</h2>
<p><em>1.</em> <em>tang Luar Negeri</em></p>
<p>Utang luar negeri adalah kewajiban keuangan yang dimiliki suatu negara kepada kreditor asing. Menurut Krugman dan Obstfeld (2018), utang luar negeri dapat berfungsi sebagai sumber pembiayaan yang penting untuk mendukung pertumbuhan ekonomi, terutama di negara-negara berkembang yang membutuhkan investasi dalam infrastruktur dan layanan publik.</p>
<p><em>2.</em> <em>Hubungan antara Utang dan Pertumbuhan Ekonomi</em></p>
<p>Penelitian oleh Eichengreen dan Hausmann (2005) menunjukkan bahwa utang luar negeri dapat memiliki dampak positif terhadap pertumbuhan ekonomi jika digunakan untuk investasi produktif. Namun, utang yang tinggi juga dapat menimbulkan risiko default dan mempengaruhi stabilitas ekonomi.</p>
<p><em>3.</em> <em>Dampak Utang terhadap GDP</em></p>
<p>Beberapa studi empiris menunjukkan bahwa terdapat hubungan non-linear antara utang luar negeri dan pertumbuhan GDP. Misalnya, penelitian oleh Cecchetti et al.&nbsp;(2011) menemukan bahwa setelah suatu ambang batas tertentu, peningkatan utang dapat menghambat pertumbuhan ekonomi, terutama di negara-negara dengan struktur ekonomi yang lemah.</p>
<p><em>4.</em> <em>Faktor Pengaruh Lainnya</em></p>
<p>Selain jumlah utang, faktor-faktor seperti kebijakan moneter, stabilitas politik, dan kondisi ekonomi global juga berperan penting dalam menentukan dampak utang luar negeri terhadap GDP. Menurut Aizenman dan Jinjarak (2013), negara-negara dengan kebijakan fiskal yang sehat dan stabilitas politik cenderung dapat mengelola utang dengan lebih baik, sehingga meminimalkan dampak negatif terhadap pertumbuhan ekonomi.</p>
<p><em>5.</em> <em>Studi Kasus Negara Berkembang</em></p>
<p>Studi oleh Ocampo dan Rada (2015) menunjukkan bahwa banyak negara berkembang mengalami kesulitan dalam mengelola utang luar negeri mereka, yang sering kali mengakibatkan pertumbuhan ekonomi yang lambat. Penelitian ini menekankan perlunya strategi pengelolaan utang yang lebih efektif untuk mendorong pertumbuhan GDP.</p>
<p><em>6.</em> <em>Kebijakan Pengelolaan Utang</em></p>
<p>Kebijakan pengelolaan utang yang baik dapat meningkatkan kemampuan suatu negara untuk memanfaatkan utang luar negeri secara produktif. Menurut Reinhart dan Rogoff (2010), negara yang memiliki kebijakan yang transparan dan akuntabel dalam pengelolaan utang cenderung lebih mampu memanfaatkan utang untuk pertumbuhan ekonomi.</p>
</section>
<section id="metode-penelitian" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metode-penelitian"><span class="header-section-number">3</span> Metode penelitian</h2>
<section id="data" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="data"><span class="header-section-number">3.1</span> Data</h3>
<p>penelitian ini menggunakan data tahun 2023 yang diperoleh dari Worldbank, sehingga didapatkan data sebagai berikut:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(WDI)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>nasywa <span class="ot">&lt;-</span> <span class="fu">WDI</span>(<span class="at">country =</span> <span class="st">"all"</span>, </span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">indicator =</span> <span class="fu">c</span>(<span class="st">"DT.DOD.DECT.CD"</span>, <span class="st">"NY.GDP.MKTP.CD"</span>), </span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">start =</span> <span class="dv">2023</span>, </span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">end =</span> <span class="dv">2023</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(nasywa)[<span class="fu">colnames</span>(nasywa) <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"DT.DOD.DECT.CD"</span>, <span class="st">"NY.GDP.MKTP.CD"</span>)] <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"X"</span>, <span class="st">"Y"</span>)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>nasywa<span class="ot">&lt;-</span> nasywa<span class="sc">%&gt;%</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>iso2c, <span class="sc">-</span>iso3c, <span class="sc">-</span>year)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(nasywa)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 67%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">country</th>
<th style="text-align: right;">X</th>
<th style="text-align: right;">Y</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Afghanistan</td>
<td style="text-align: right;">3.428117e+09</td>
<td style="text-align: right;">1.723305e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Africa Eastern and Southern</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1.245472e+12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Africa Western and Central</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">7.991060e+11</td>
</tr>
<tr class="even">
<td style="text-align: left;">Albania</td>
<td style="text-align: right;">1.136395e+10</td>
<td style="text-align: right;">2.354718e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Algeria</td>
<td style="text-align: right;">7.315266e+09</td>
<td style="text-align: right;">2.476262e+11</td>
</tr>
<tr class="even">
<td style="text-align: left;">American Samoa</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Andorra</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">3.785067e+09</td>
</tr>
<tr class="even">
<td style="text-align: left;">Angola</td>
<td style="text-align: right;">5.703175e+10</td>
<td style="text-align: right;">8.482465e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Antigua and Barbuda</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">2.033085e+09</td>
</tr>
<tr class="even">
<td style="text-align: left;">Arab World</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">3.512421e+12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Argentina</td>
<td style="text-align: right;">2.661673e+11</td>
<td style="text-align: right;">6.460753e+11</td>
</tr>
<tr class="even">
<td style="text-align: left;">Armenia</td>
<td style="text-align: right;">1.583883e+10</td>
<td style="text-align: right;">2.408575e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Aruba</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">3.648573e+09</td>
</tr>
<tr class="even">
<td style="text-align: left;">Australia</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1.728057e+12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Austria</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">5.116852e+11</td>
</tr>
<tr class="even">
<td style="text-align: left;">Azerbaijan</td>
<td style="text-align: right;">1.453268e+10</td>
<td style="text-align: right;">7.235618e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bahamas, The</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1.433850e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bahrain</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">4.607987e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bangladesh</td>
<td style="text-align: right;">1.014475e+11</td>
<td style="text-align: right;">4.374153e+11</td>
</tr>
<tr class="even">
<td style="text-align: left;">Barbados</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">6.720733e+09</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Belarus</td>
<td style="text-align: right;">3.670454e+10</td>
<td style="text-align: right;">7.185738e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Belgium</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">6.447828e+11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Belize</td>
<td style="text-align: right;">1.509919e+09</td>
<td style="text-align: right;">3.066850e+09</td>
</tr>
<tr class="even">
<td style="text-align: left;">Benin</td>
<td style="text-align: right;">1.248275e+10</td>
<td style="text-align: right;">1.967605e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bermuda</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">8.141700e+09</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bhutan</td>
<td style="text-align: right;">3.269071e+09</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bolivia</td>
<td style="text-align: right;">1.630694e+10</td>
<td style="text-align: right;">4.513540e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bosnia and Herzegovina</td>
<td style="text-align: right;">1.401019e+10</td>
<td style="text-align: right;">2.751478e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Botswana</td>
<td style="text-align: right;">2.078816e+09</td>
<td style="text-align: right;">1.939608e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Brazil</td>
<td style="text-align: right;">6.071155e+11</td>
<td style="text-align: right;">2.173666e+12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">British Virgin Islands</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">Brunei Darussalam</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1.512829e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bulgaria</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1.024077e+11</td>
</tr>
<tr class="even">
<td style="text-align: left;">Burkina Faso</td>
<td style="text-align: right;">1.039739e+10</td>
<td style="text-align: right;">2.032462e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Burundi</td>
<td style="text-align: right;">1.042822e+09</td>
<td style="text-align: right;">2.642162e+09</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cabo Verde</td>
<td style="text-align: right;">2.451446e+09</td>
<td style="text-align: right;">2.533819e+09</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cambodia</td>
<td style="text-align: right;">2.253361e+10</td>
<td style="text-align: right;">4.233565e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cameroon</td>
<td style="text-align: right;">1.529927e+10</td>
<td style="text-align: right;">4.927941e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Canada</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">2.142471e+12</td>
</tr>
<tr class="even">
<td style="text-align: left;">Caribbean small states</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">5.329616e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cayman Islands</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">7.139429e+09</td>
</tr>
<tr class="even">
<td style="text-align: left;">Central African Republic</td>
<td style="text-align: right;">1.020876e+09</td>
<td style="text-align: right;">2.555492e+09</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Central Europe and the Baltics</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">2.267761e+12</td>
</tr>
<tr class="even">
<td style="text-align: left;">Chad</td>
<td style="text-align: right;">3.214042e+09</td>
<td style="text-align: right;">1.314933e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Channel Islands</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1.250793e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Chile</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">3.355333e+11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">China</td>
<td style="text-align: right;">2.420211e+12</td>
<td style="text-align: right;">1.779478e+13</td>
</tr>
<tr class="even">
<td style="text-align: left;">Colombia</td>
<td style="text-align: right;">1.975052e+11</td>
<td style="text-align: right;">3.634938e+11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Comoros</td>
<td style="text-align: right;">4.093405e+08</td>
<td style="text-align: right;">1.352381e+09</td>
</tr>
<tr class="even">
<td style="text-align: left;">Congo, Dem. Rep.</td>
<td style="text-align: right;">1.106689e+10</td>
<td style="text-align: right;">6.638329e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Congo, Rep.</td>
<td style="text-align: right;">7.779156e+09</td>
<td style="text-align: right;">1.532106e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Costa Rica</td>
<td style="text-align: right;">3.902512e+10</td>
<td style="text-align: right;">8.649794e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cote d’Ivoire</td>
<td style="text-align: right;">3.654788e+10</td>
<td style="text-align: right;">7.887549e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Croatia</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">8.439380e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cuba</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">Curacao</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">3.281419e+09</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cyprus</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">3.388693e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Czechia</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">3.432079e+11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Denmark</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">4.070919e+11</td>
</tr>
<tr class="even">
<td style="text-align: left;">Djibouti</td>
<td style="text-align: right;">3.428663e+09</td>
<td style="text-align: right;">4.098531e+09</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Dominica</td>
<td style="text-align: right;">5.981359e+08</td>
<td style="text-align: right;">6.539926e+08</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dominican Republic</td>
<td style="text-align: right;">5.225663e+10</td>
<td style="text-align: right;">1.214443e+11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Early-demographic dividend</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1.494590e+13</td>
</tr>
<tr class="even">
<td style="text-align: left;">East Asia &amp; Pacific (excluding high income)</td>
<td style="text-align: right;">3.392852e+12</td>
<td style="text-align: right;">2.116284e+13</td>
</tr>
<tr class="odd">
<td style="text-align: left;">East Asia &amp; Pacific (IDA &amp; IBRD countries)</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">2.113671e+13</td>
</tr>
<tr class="even">
<td style="text-align: left;">East Asia &amp; Pacific</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">3.078018e+13</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ecuador</td>
<td style="text-align: right;">6.056362e+10</td>
<td style="text-align: right;">1.188448e+11</td>
</tr>
<tr class="even">
<td style="text-align: left;">Egypt, Arab Rep.</td>
<td style="text-align: right;">1.680623e+11</td>
<td style="text-align: right;">3.960025e+11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">El Salvador</td>
<td style="text-align: right;">2.274150e+10</td>
<td style="text-align: right;">3.401562e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Equatorial Guinea</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1.233755e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Eritrea</td>
<td style="text-align: right;">7.127791e+08</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">Estonia</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">4.129125e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Eswatini</td>
<td style="text-align: right;">1.240688e+09</td>
<td style="text-align: right;">4.442876e+09</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ethiopia</td>
<td style="text-align: right;">3.329027e+10</td>
<td style="text-align: right;">1.636979e+11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Euro area</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1.578069e+13</td>
</tr>
<tr class="even">
<td style="text-align: left;">Europe &amp; Central Asia (excluding high income)</td>
<td style="text-align: right;">1.121762e+12</td>
<td style="text-align: right;">2.129704e+12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Europe &amp; Central Asia (IDA &amp; IBRD countries)</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">5.497904e+12</td>
</tr>
<tr class="even">
<td style="text-align: left;">Europe &amp; Central Asia</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">2.755407e+13</td>
</tr>
<tr class="odd">
<td style="text-align: left;">European Union</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1.859072e+13</td>
</tr>
<tr class="even">
<td style="text-align: left;">Faroe Islands</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">3.907324e+09</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Fiji</td>
<td style="text-align: right;">3.347682e+09</td>
<td style="text-align: right;">5.442047e+09</td>
</tr>
<tr class="even">
<td style="text-align: left;">Finland</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">2.955323e+11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Fragile and conflict affected situations</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1.937937e+12</td>
</tr>
<tr class="even">
<td style="text-align: left;">France</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">3.051832e+12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">French Polynesia</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gabon</td>
<td style="text-align: right;">7.588100e+09</td>
<td style="text-align: right;">1.938840e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gambia, The</td>
<td style="text-align: right;">1.325049e+09</td>
<td style="text-align: right;">2.396111e+09</td>
</tr>
<tr class="even">
<td style="text-align: left;">Georgia</td>
<td style="text-align: right;">2.446754e+10</td>
<td style="text-align: right;">3.077783e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Germany</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">4.525704e+12</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ghana</td>
<td style="text-align: right;">4.374198e+10</td>
<td style="text-align: right;">7.637040e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gibraltar</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">Greece</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">2.434983e+11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Greenland</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">Grenada</td>
<td style="text-align: right;">7.271419e+08</td>
<td style="text-align: right;">1.316733e+09</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Guam</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">Guatemala</td>
<td style="text-align: right;">2.536485e+10</td>
<td style="text-align: right;">1.044502e+11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Guinea-Bissau</td>
<td style="text-align: right;">1.128037e+09</td>
<td style="text-align: right;">2.048348e+09</td>
</tr>
<tr class="even">
<td style="text-align: left;">Guinea</td>
<td style="text-align: right;">5.164136e+09</td>
<td style="text-align: right;">2.219941e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Guyana</td>
<td style="text-align: right;">2.952574e+09</td>
<td style="text-align: right;">1.715951e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Haiti</td>
<td style="text-align: right;">2.637610e+09</td>
<td style="text-align: right;">1.985083e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Heavily indebted poor countries (HIPC)</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1.129947e+12</td>
</tr>
<tr class="even">
<td style="text-align: left;">High income</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">6.827649e+13</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Honduras</td>
<td style="text-align: right;">1.282058e+10</td>
<td style="text-align: right;">3.440051e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hong Kong SAR, China</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">3.808122e+11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hungary</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">2.123889e+11</td>
</tr>
<tr class="even">
<td style="text-align: left;">IBRD only</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">3.878930e+13</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Iceland</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">3.132512e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">IDA &amp; IBRD total</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">4.166901e+13</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IDA blend</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1.068438e+12</td>
</tr>
<tr class="even">
<td style="text-align: left;">IDA only</td>
<td style="text-align: right;">7.363180e+11</td>
<td style="text-align: right;">1.814047e+12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IDA total</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">2.880515e+12</td>
</tr>
<tr class="even">
<td style="text-align: left;">India</td>
<td style="text-align: right;">6.467871e+11</td>
<td style="text-align: right;">3.567552e+12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Indonesia</td>
<td style="text-align: right;">4.060544e+11</td>
<td style="text-align: right;">1.371171e+12</td>
</tr>
<tr class="even">
<td style="text-align: left;">Iran, Islamic Rep.</td>
<td style="text-align: right;">9.900873e+09</td>
<td style="text-align: right;">4.046257e+11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Iraq</td>
<td style="text-align: right;">2.033139e+10</td>
<td style="text-align: right;">2.508428e+11</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ireland</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">5.513949e+11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Isle of Man</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">Israel</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">5.136111e+11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Italy</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">2.300941e+12</td>
</tr>
<tr class="even">
<td style="text-align: left;">Jamaica</td>
<td style="text-align: right;">1.534942e+10</td>
<td style="text-align: right;">1.942336e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Japan</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">4.204495e+12</td>
</tr>
<tr class="even">
<td style="text-align: left;">Jordan</td>
<td style="text-align: right;">4.462984e+10</td>
<td style="text-align: right;">5.096748e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Kazakhstan</td>
<td style="text-align: right;">1.631545e+11</td>
<td style="text-align: right;">2.626419e+11</td>
</tr>
<tr class="even">
<td style="text-align: left;">Kenya</td>
<td style="text-align: right;">4.291003e+10</td>
<td style="text-align: right;">1.080386e+11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Kiribati</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">2.792089e+08</td>
</tr>
<tr class="even">
<td style="text-align: left;">Korea, Dem. People’s Rep.</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Korea, Rep.</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1.712793e+12</td>
</tr>
<tr class="even">
<td style="text-align: left;">Kosovo</td>
<td style="text-align: right;">4.242269e+09</td>
<td style="text-align: right;">1.046822e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Kuwait</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1.637049e+11</td>
</tr>
<tr class="even">
<td style="text-align: left;">Kyrgyz Republic</td>
<td style="text-align: right;">1.011505e+10</td>
<td style="text-align: right;">1.398763e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Lao PDR</td>
<td style="text-align: right;">2.008864e+10</td>
<td style="text-align: right;">1.584316e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Late-demographic dividend</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">2.834848e+13</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Latin America &amp; Caribbean (excluding high income)</td>
<td style="text-align: right;">2.053962e+12</td>
<td style="text-align: right;">6.057470e+12</td>
</tr>
<tr class="even">
<td style="text-align: left;">Latin America &amp; Caribbean</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">7.100142e+12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Latin America &amp; the Caribbean (IDA &amp; IBRD countries)</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">6.779682e+12</td>
</tr>
<tr class="even">
<td style="text-align: left;">Latvia</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">4.224785e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Least developed countries: UN classification</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1.516989e+12</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lebanon</td>
<td style="text-align: right;">6.629646e+10</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Lesotho</td>
<td style="text-align: right;">1.775614e+09</td>
<td style="text-align: right;">2.117962e+09</td>
</tr>
<tr class="even">
<td style="text-align: left;">Liberia</td>
<td style="text-align: right;">2.078057e+09</td>
<td style="text-align: right;">4.240000e+09</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Libya</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">4.509646e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Liechtenstein</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Lithuania</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">7.978988e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Low &amp; middle income</td>
<td style="text-align: right;">8.836507e+12</td>
<td style="text-align: right;">3.753377e+13</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Low income</td>
<td style="text-align: right;">2.319755e+11</td>
<td style="text-align: right;">6.635292e+11</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lower middle income</td>
<td style="text-align: right;">2.257898e+12</td>
<td style="text-align: right;">7.439509e+12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Luxembourg</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">8.575501e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Macao SAR, China</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">4.580307e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Madagascar</td>
<td style="text-align: right;">6.452329e+09</td>
<td style="text-align: right;">1.579011e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Malawi</td>
<td style="text-align: right;">3.604446e+09</td>
<td style="text-align: right;">1.271215e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Malaysia</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">3.997052e+11</td>
</tr>
<tr class="even">
<td style="text-align: left;">Maldives</td>
<td style="text-align: right;">4.000222e+09</td>
<td style="text-align: right;">6.590894e+09</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mali</td>
<td style="text-align: right;">6.457154e+09</td>
<td style="text-align: right;">2.066179e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Malta</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">2.232864e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Marshall Islands</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">2.593000e+08</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mauritania</td>
<td style="text-align: right;">4.603557e+09</td>
<td style="text-align: right;">1.065171e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mauritius</td>
<td style="text-align: right;">1.925234e+10</td>
<td style="text-align: right;">1.464452e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mexico</td>
<td style="text-align: right;">5.959177e+11</td>
<td style="text-align: right;">1.789114e+12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Micronesia, Fed. Sts.</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">4.600000e+08</td>
</tr>
<tr class="even">
<td style="text-align: left;">Middle East &amp; North Africa (excluding high income)</td>
<td style="text-align: right;">4.426693e+11</td>
<td style="text-align: right;">1.671175e+12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Middle East &amp; North Africa (IDA &amp; IBRD countries)</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1.653767e+12</td>
</tr>
<tr class="even">
<td style="text-align: left;">Middle East &amp; North Africa</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">4.320567e+12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Middle income</td>
<td style="text-align: right;">8.604532e+12</td>
<td style="text-align: right;">3.687812e+13</td>
</tr>
<tr class="even">
<td style="text-align: left;">Moldova</td>
<td style="text-align: right;">1.063868e+10</td>
<td style="text-align: right;">1.653944e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Monaco</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">9.995351e+09</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mongolia</td>
<td style="text-align: right;">3.432129e+10</td>
<td style="text-align: right;">2.032512e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Montenegro</td>
<td style="text-align: right;">8.616499e+09</td>
<td style="text-align: right;">7.530593e+09</td>
</tr>
<tr class="even">
<td style="text-align: left;">Morocco</td>
<td style="text-align: right;">6.926728e+10</td>
<td style="text-align: right;">1.444171e+11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mozambique</td>
<td style="text-align: right;">6.684772e+10</td>
<td style="text-align: right;">2.095422e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Myanmar</td>
<td style="text-align: right;">1.216210e+10</td>
<td style="text-align: right;">6.675762e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Namibia</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1.235103e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Nauru</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1.541703e+08</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Nepal</td>
<td style="text-align: right;">9.968496e+09</td>
<td style="text-align: right;">4.090807e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Netherlands</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1.154361e+12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">New Caledonia</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">New Zealand</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">2.521755e+11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Nicaragua</td>
<td style="text-align: right;">1.516341e+10</td>
<td style="text-align: right;">1.782922e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Niger</td>
<td style="text-align: right;">5.612995e+09</td>
<td style="text-align: right;">1.681917e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Nigeria</td>
<td style="text-align: right;">1.024817e+11</td>
<td style="text-align: right;">3.638463e+11</td>
</tr>
<tr class="even">
<td style="text-align: left;">North America</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">2.987132e+13</td>
</tr>
<tr class="odd">
<td style="text-align: left;">North Macedonia</td>
<td style="text-align: right;">1.261429e+10</td>
<td style="text-align: right;">1.576362e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Northern Mariana Islands</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Norway</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">4.853108e+11</td>
</tr>
<tr class="even">
<td style="text-align: left;">Not classified</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">OECD members</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">6.474656e+13</td>
</tr>
<tr class="even">
<td style="text-align: left;">Oman</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1.088109e+11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Other small states</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">2.410865e+11</td>
</tr>
<tr class="even">
<td style="text-align: left;">Pacific island small states</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1.115070e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Pakistan</td>
<td style="text-align: right;">1.308474e+11</td>
<td style="text-align: right;">3.379123e+11</td>
</tr>
<tr class="even">
<td style="text-align: left;">Palau</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">2.818491e+08</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Panama</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">8.331818e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Papua New Guinea</td>
<td style="text-align: right;">1.532062e+10</td>
<td style="text-align: right;">3.072924e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Paraguay</td>
<td style="text-align: right;">2.636132e+10</td>
<td style="text-align: right;">4.295626e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Peru</td>
<td style="text-align: right;">9.006757e+10</td>
<td style="text-align: right;">2.676032e+11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Philippines</td>
<td style="text-align: right;">1.214021e+11</td>
<td style="text-align: right;">4.371464e+11</td>
</tr>
<tr class="even">
<td style="text-align: left;">Poland</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">8.092007e+11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Portugal</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">2.891143e+11</td>
</tr>
<tr class="even">
<td style="text-align: left;">Post-demographic dividend</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">6.048525e+13</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Pre-demographic dividend</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1.566942e+12</td>
</tr>
<tr class="even">
<td style="text-align: left;">Puerto Rico</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1.179023e+11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Qatar</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">2.130028e+11</td>
</tr>
<tr class="even">
<td style="text-align: left;">Romania</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">3.507759e+11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Russian Federation</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">2.021421e+12</td>
</tr>
<tr class="even">
<td style="text-align: left;">Rwanda</td>
<td style="text-align: right;">1.138398e+10</td>
<td style="text-align: right;">1.409777e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Samoa</td>
<td style="text-align: right;">4.324949e+08</td>
<td style="text-align: right;">9.381894e+08</td>
</tr>
<tr class="even">
<td style="text-align: left;">San Marino</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sao Tome and Principe</td>
<td style="text-align: right;">4.542730e+08</td>
<td style="text-align: right;">6.789763e+08</td>
</tr>
<tr class="even">
<td style="text-align: left;">Saudi Arabia</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1.067583e+12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Senegal</td>
<td style="text-align: right;">3.995011e+10</td>
<td style="text-align: right;">3.084833e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Serbia</td>
<td style="text-align: right;">4.900013e+10</td>
<td style="text-align: right;">8.134266e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Seychelles</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">2.141450e+09</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sierra Leone</td>
<td style="text-align: right;">2.381922e+09</td>
<td style="text-align: right;">6.411870e+09</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Singapore</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">5.014275e+11</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sint Maarten (Dutch part)</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1.627777e+09</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Slovak Republic</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1.329083e+11</td>
</tr>
<tr class="even">
<td style="text-align: left;">Slovenia</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">6.914847e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Small states</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">3.055467e+11</td>
</tr>
<tr class="even">
<td style="text-align: left;">Solomon Islands</td>
<td style="text-align: right;">5.278176e+08</td>
<td style="text-align: right;">1.633319e+09</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Somalia</td>
<td style="text-align: right;">3.022834e+09</td>
<td style="text-align: right;">1.096852e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">South Africa</td>
<td style="text-align: right;">1.657866e+11</td>
<td style="text-align: right;">3.806993e+11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">South Asia (IDA &amp; IBRD)</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">4.494987e+12</td>
</tr>
<tr class="even">
<td style="text-align: left;">South Asia</td>
<td style="text-align: right;">9.614538e+11</td>
<td style="text-align: right;">4.494987e+12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">South Sudan</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">Spain</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1.620091e+12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sri Lanka</td>
<td style="text-align: right;">6.170595e+10</td>
<td style="text-align: right;">8.435686e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">St.&nbsp;Kitts and Nevis</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1.055500e+09</td>
</tr>
<tr class="odd">
<td style="text-align: left;">St.&nbsp;Lucia</td>
<td style="text-align: right;">1.086264e+09</td>
<td style="text-align: right;">2.430148e+09</td>
</tr>
<tr class="even">
<td style="text-align: left;">St.&nbsp;Martin (French part)</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">St.&nbsp;Vincent and the Grenadines</td>
<td style="text-align: right;">6.285087e+08</td>
<td style="text-align: right;">1.065963e+09</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sub-Saharan Africa (excluding high income)</td>
<td style="text-align: right;">8.638087e+11</td>
<td style="text-align: right;">2.042437e+12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sub-Saharan Africa (IDA &amp; IBRD countries)</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">2.044578e+12</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sub-Saharan Africa</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">2.044578e+12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sudan</td>
<td style="text-align: right;">2.258057e+10</td>
<td style="text-align: right;">1.092655e+11</td>
</tr>
<tr class="even">
<td style="text-align: left;">Suriname</td>
<td style="text-align: right;">4.047563e+09</td>
<td style="text-align: right;">3.455146e+09</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sweden</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">5.849605e+11</td>
</tr>
<tr class="even">
<td style="text-align: left;">Switzerland</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">8.849404e+11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Syrian Arab Republic</td>
<td style="text-align: right;">4.875543e+09</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tajikistan</td>
<td style="text-align: right;">6.872766e+09</td>
<td style="text-align: right;">1.206060e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Tanzania</td>
<td style="text-align: right;">3.459795e+10</td>
<td style="text-align: right;">7.906240e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Thailand</td>
<td style="text-align: right;">1.936262e+11</td>
<td style="text-align: right;">5.149687e+11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Timor-Leste</td>
<td style="text-align: right;">3.073840e+08</td>
<td style="text-align: right;">2.079917e+09</td>
</tr>
<tr class="even">
<td style="text-align: left;">Togo</td>
<td style="text-align: right;">3.375209e+09</td>
<td style="text-align: right;">9.171262e+09</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Tonga</td>
<td style="text-align: right;">1.964535e+08</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">Trinidad and Tobago</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">2.737229e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Tunisia</td>
<td style="text-align: right;">4.127870e+10</td>
<td style="text-align: right;">4.852960e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Turkiye</td>
<td style="text-align: right;">4.998425e+11</td>
<td style="text-align: right;">1.118253e+12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Turkmenistan</td>
<td style="text-align: right;">3.917748e+09</td>
<td style="text-align: right;">6.062886e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Turks and Caicos Islands</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1.402054e+09</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Tuvalu</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">6.228031e+07</td>
</tr>
<tr class="even">
<td style="text-align: left;">Uganda</td>
<td style="text-align: right;">1.939347e+10</td>
<td style="text-align: right;">4.876896e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ukraine</td>
<td style="text-align: right;">1.766455e+11</td>
<td style="text-align: right;">1.787570e+11</td>
</tr>
<tr class="even">
<td style="text-align: left;">United Arab Emirates</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">5.141304e+11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">United Kingdom</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">3.380855e+12</td>
</tr>
<tr class="even">
<td style="text-align: left;">United States</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">2.772071e+13</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Upper middle income</td>
<td style="text-align: right;">6.346633e+12</td>
<td style="text-align: right;">2.944002e+13</td>
</tr>
<tr class="even">
<td style="text-align: left;">Uruguay</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">7.724083e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Uzbekistan</td>
<td style="text-align: right;">5.918435e+10</td>
<td style="text-align: right;">1.015918e+11</td>
</tr>
<tr class="even">
<td style="text-align: left;">Vanuatu</td>
<td style="text-align: right;">4.706637e+08</td>
<td style="text-align: right;">1.126313e+09</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Venezuela, RB</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">Viet Nam</td>
<td style="text-align: right;">1.418496e+11</td>
<td style="text-align: right;">4.297170e+11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Virgin Islands (U.S.)</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">West Bank and Gaza</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1.742080e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">World</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1.061717e+14</td>
</tr>
<tr class="even">
<td style="text-align: left;">Yemen, Rep.</td>
<td style="text-align: right;">7.283022e+09</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zambia</td>
<td style="text-align: right;">2.957893e+10</td>
<td style="text-align: right;">2.757796e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Zimbabwe</td>
<td style="text-align: right;">1.421339e+10</td>
<td style="text-align: right;">3.523137e+10</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(writexl)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">write_xlsx</span>(nasywa,<span class="st">"nasywa.xlsx"</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(nasywa)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"ggplot2"</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"readxl"</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"dplyr"</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>nasywa,<span class="fu">aes</span>(<span class="at">x=</span>X,<span class="at">y=</span>Y))<span class="sc">+</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color=</span><span class="st">"violet"</span>,<span class="at">size=</span><span class="dv">2</span>)<span class="sc">+</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Hubungan External Debt Stock terhadap GDP Tahun 2023"</span>,</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x=</span><span class="st">"External Debt Stock"</span>,</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y=</span><span class="st">"GDP"</span>,</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"sumber: data.worldbank.org"</span>)<span class="sc">+</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="metode-analisis" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="metode-analisis"><span class="header-section-number">3.2</span> Metode analisis</h3>
<p>Penelitian ini menggunakan metode regresi univariat atau Ordinary Least Square (OLS) dengan satu variabel independen. Tujuan penelitian ini adalah untuk menganalisis hubungan antara utang luar negeri suatu negara dengan Produk Domestik Bruto (GDP). Model yang digunakan dirancang secara spesifik untuk menggambarkan keterkaitan antara kedua variabel, sebagai berikut:</p>
<p><span class="math display">\[
y_{t}=\beta_0 + \beta_1 x_t+\mu_t
\]</span> di mana <span class="math inline">\(y_t\)</span> adalah GDP dan <span class="math inline">\(x_t\)</span> adalah External Debt Stock.</p>
</section>
</section>
<section id="pembahasan" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="pembahasan"><span class="header-section-number">4</span> Pembahasan</h2>
<section id="pembahasan-masalah" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="pembahasan-masalah"><span class="header-section-number">4.1</span> Pembahasan masalah</h3>
<p>Regresi yang telah dilakukan, menghasilkan data sebgai berikut:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>variable</th>
<th>Coefficients</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>-8.355e+10</td>
</tr>
<tr class="even">
<td>X</td>
<td>4.454e+00</td>
</tr>
<tr class="odd">
<td>p-value</td>
<td>&lt; 2.2e-16</td>
</tr>
<tr class="even">
<td>Multiple R-squared</td>
<td>0.9702</td>
</tr>
<tr class="odd">
<td>Adjusted R-squared</td>
<td>0.97</td>
</tr>
</tbody>
</table>
<p>Sehingga dapat di implementasikan sebagai berikut: <span class="math display">\[
y_{t}=\ (-8.355e+10) + \ (4.454e+00)+\mu_t
\]</span></p>
<p>Koefisien intercept (β0) sebesar -8.355e+10 menunjukkan bahwa jika utang luar negeri(X) bernilai nol, GDP (Y) diprediksi sebesar −83.55 miliar. Namun, dalam konteks ekonomi, nilai ini hampir tidak mungkin suatu negara memiliki utang luar negeri nol. Koefisien X(β1) sebesar 4.454e+00 menunjukkan bahwa setiap peningkatan satu satuan pada utang luar negeri diasosiasikan dengan peningkatan GDP sebesar 4.454 unit. Koefisien ini signifikan secara statistik, dengan p-value &lt; 2e-16, yang menunjukkan hubungan kuat antara utang luar negeri dan GDP.</p>
<p>Hubungan positif tidak selalu berarti bahwa utang secara langsung meningkatkan GDP. Kemungkinan besar, negara-negara dengan GDP besar juga memiliki kapasitas untuk mengambil utang lebih banyak karena mereka dianggap lebih mampu membayar kembali utang tersebut.</p>
<p>Koefisien positif bisa terjadi jika sebagian besar negara dalam data penelitian menggunakan utang mereka untuk kegiatan produktif seperti pembangunan infrastruktur atau peningkatan kapasitas industri. Hal ini membantu meningkatkan output ekonomi yang direfleksikan dalam GDP.</p>
</section>
<section id="analisis-masalah" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="analisis-masalah"><span class="header-section-number">4.2</span> Analisis masalah</h3>
<p>Hasil regresinya adalah</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>nasywa<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"nasywa.xlsx"</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>reg<span class="ot">&lt;-</span><span class="fu">lm</span>(Y<span class="sc">~</span>X,<span class="at">data=</span>nasywa)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Y ~ X, data = nasywa)

Residuals:
       Min         1Q     Median         3Q        Max 
-3.007e+12 -5.134e+10  5.576e+10  8.144e+10  7.099e+12 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -8.355e+10  9.360e+10  -0.893    0.374    
X            4.454e+00  7.008e-02  63.556   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.013e+12 on 124 degrees of freedom
  (140 observations deleted due to missingness)
Multiple R-squared:  0.9702,    Adjusted R-squared:   0.97 
F-statistic:  4039 on 1 and 124 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Median residual yang positif (5.576e+10) menunjukkan bahwa sebagian besar data lebih cenderung memberikan prediksi lebih besar dari nilai observasi. Model ini memiliki kecocokan yang sangat baik dengan data, dengan Multiple R-squared sebesar 0.9702, yang berarti sekitar 97.02% variasi dalam Y dapat dijelaskan oleh X. Nilai Adjusted R-squared yang sedikit lebih rendah (0.97) juga mendukung kecocokan model setelah mempertimbangkan jumlah prediktor yang digunakan.</p>
<p>Statistik F sebesar 4039 dengan nilai p &lt; 2.2e-16 mengindikasikan bahwa model secara keseluruhan signifikan, yang berarti bahwa variabel X memiliki pengaruh yang sangat kuat terhadap Y. Meskipun model ini menunjukkan kecocokan yang sangat baik dan kemampuan prediksi yang tinggi, masalah residual yang sangat besar perlu diperhatikan, karena dapat menunjukkan adanya outliers atau adanya variabel lain yang belum dimasukkan dalam model. Secara keseluruhan, model ini dapat diandalkan dalam menjelaskan hubungan antara X dan Y, namun analisis lebih lanjut diperlukan untuk menangani masalah residual yang besar.</p>
</section>
</section>
<section id="kesimpulan" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="kesimpulan"><span class="header-section-number">5</span> Kesimpulan</h2>
<p>Kesimpulan dari penelitian ini menunjukkan bahwa utang luar negeri memiliki pengaruh signifikan terhadap Produk Domestik Bruto (GDP) di negara berkembang, khususnya Indonesia. Berdasarkan analisis regresi yang dilakukan, ditemukan bahwa setiap peningkatan satu unit pada stok utang luar negeri berhubungan dengan peningkatan GDP sebesar 4.454 unit. Koefisien regresi yang signifikan dengan nilai p-value yang sangat kecil menunjukkan adanya hubungan yang kuat antara kedua variabel tersebut. Model yang digunakan dalam penelitian ini juga menunjukkan kecocokan yang sangat baik dengan data, dengan nilai R-squared sebesar 0.9702, yang berarti bahwa 97.02% variasi dalam GDP dapat dijelaskan oleh stok utang luar negeri.</p>
<p>Namun, meskipun terdapat hubungan positif antara utang luar negeri dan GDP, perlu dicatat bahwa utang yang tinggi bisa berisiko jika tidak dikelola dengan baik. Sumber daya yang digunakan untuk membayar utang bisa mengalihkan perhatian dari pengeluaran produktif, sehingga mempengaruhi pertumbuhan ekonomi dalam jangka panjang.</p>
</section>
<section id="referensi" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="referensi"><span class="header-section-number">6</span> Referensi</h2>
<p>https://id.tradingeconomics.com Trade Economic</p>
<p>https://www.bps.go.id/id BPS</p>
<p>https://www.worldbank.org/ext/en/home World Bank</p>
<p>Aizenman, J., &amp; Jinjarak, Y. (2013). The Financial Crisis and Its Aftermath: What’s the New Normal? Journal of International Money and Finance.</p>
<p>Cecchetti, S. G., Mohanty, M. S., &amp; Zampolli, F. (2011). The Real Effects of Debt. BIS Working Papers.</p>
<p>Eichengreen, B., &amp; Hausmann, R. (2005). Other People’s Money: Debt Denomination and Financial Instability in Emerging Market Economies. University of Chicago Press.</p>
<p>Krugman, P., &amp; Obstfeld, M. (2018). International Economics: Theory and Policy. Pearson. Ocampo, J. A., &amp; Rada, C. (2015). The Economics of the Global Financial Crisis. Cambridge University Press.</p>
<p>Reinhart, C. M., &amp; Rogoff, K. S. (2010). This Time Is Different: Eight Centuries of Financial Folly. Princeton University Press.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>